### ISSUE TITLE
Need editable version

### ISSUE THREAD

**Issue by MutahirAli** [javachessgui/javachessgui#1]
Can I get the editable code of this project Sir? I need to use this javachessgui in my final year project but for that, i had to make some changes but I can't make changes in the current version as its a jar file. ?

**Comment by javachessgui** [comment]
I don't really understand this question. What is "editable" code? The source code is there, you can create a project from it and compile it. If you manage to compile it, then you can make modifications to the source and compile the modified source. I compiled it in NetBeans. I switched to Scala sbt since, but as far as I remember NetBeans creates a .jar.

**Comment by MutahirAli** [comment]
thanks for your reply sir
i know that i can make modifications in the source code but I think that I
asked a wrong question.
the problem is I can't access the chessGUI because its a jar file and need
the code of that jar file so that i can access the GUI
did u get my question now?

**Comment by javachessgui** [comment]
The .jar is a Java executable, it is essentially a zipped version the compiled classes ( "byte code" ) of the application. When you run it is first unzipped and then the JVM ( Java Virtual Machine ) loads the compiled classes and runs them. You just click on it and it runs. I gave detailed instructions in the ReadMe how to run the .jar ( when you download the zipped repo, you also download the .jar, it is in the dist folder : https://github.com/javachessgui/javachessgui/tree/master/dist ). You can open the .jar in a zip browser ( for example 7z has one and it is free ) to see for yourself what is contained in the .jar. If you have problems running the .jar it may be that your JVM is too old, update it to the latest version ( Java8+ ).

**Comment by MutahirAli** [comment]
I am using javachessgui since last 3 months, its running on compiler and
also directly jar file is also running. and i know that source code is also
there.
But the problem is I can't access the GUI code like if i want to edit the
code behind any button using "on click" or any other method..i m unable to
access that.

**Comment by javachessgui** [comment]
For example there is the board flip button. Its event handler is set here:

https://github.com/javachessgui/javachessgui/blob/master/src/javachessgui/Board.java#L2812

So whenever you press the flip button, the function flip() will be called.

The flip() function is defined here:

https://github.com/javachessgui/javachessgui/blob/master/src/javachessgui/Board.java#L1371

You can edit this function, for example add a command that prints something on the console, run the application with a console window ( or in the compiler's debugger ), press the flip button and see if something is printed. If you manage to do this, than you can find and edit the other button handlers, they are mostly in Board.java and Game.java.
