### ISSUE TITLE
Convert to android

### ISSUE THREAD

**Issue by MutahirAli** [javachessgui/javachessgui#2]
it may seem a bit off topic after reading your mail about Scala Update in javachessgui.
Still, i want to ask that can we convert javachessgui from javafx to Android platform??

**Comment by javachessgui** [comment]
I have no clue about how to write an Android JavaFX application or how to transform an existing one to Android. This program was intended as a desktop application. Currently I'm working on a web application seed which integrates server and client side code in a single Scala project ( server side being Play Framework and client side Javascript generated with Scala.js ), so I'm not likely to touch JavaFX in the near future.

**Comment by MutahirAli** [comment]
Hi sir
I 'm sorry to disturb u again and again but I m using your chess editor in
my final year project. this time I m just unable to understand the working
of a chess engine in your editor. I have tried loading several chess
engines but when I open any specific PGN file, most probably any puzzle
PGN. it does not suggest me any moves neither tells either move is right or
wrong.
if you have made any demo related to working of javachessgui and how an
engine can be loaded or used? kindly guide me about this?
i shall be very thankful to you for this favor.

**Comment by javachessgui** [comment]
You just press the "Load engine" button, then select an engine with the file chooser of your system, then double click on it. Note that the engine has to be a UCI engine. XBOARD or other engines won't work. Stockfish is a UCI engine, that I recommend. Once the engine has loaded you should see its opening message in the textbox below the board. Then press the "Go" button and it will start analyzing.

Should look something like this:
![jcgsearch](https://user-images.githubusercontent.com/12657385/27263746-0486f4aa-5470-11e7-8806-b8e6972e6e7f.PNG)

**Comment by MutahirAli** [comment]
yeah, it worked thank you very much. i was loading engine the same way and
trying but the problem was with the engine. it was without UCI.
Thank you
